services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    environment:
      DOMAIN: "$VAULTWARDEN_DOMAIN"
    volumes:
      - ./vw-data/:/data/
    ports:
      - 81:80