# More info https://docs.pi-hole.net/
services:
  cloudflared:
    container_name: cloudflared
    restart: unless-stopped
    image: cloudflare/cloudflared:latest
    command: proxy-dns
    environment:
      - "TUNNEL_DNS_UPSTREAM=https://1.1.1.1/dns-query,https://1.0.0.1/dns-query,https://9.9.9.9/dns-query"
      - "TUNNEL_DNS_PORT=5053"
      - "TUNNEL_DNS_ADDRESS=0.0.0.0"
    networks:
      pihole_internal:
        ipv4_address: 172.70.7.2
    security_opt:
      - no-new-privileges:true

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "500:80/tcp"
    networks:
      pihole_internal:
        ipv4_address: 172.70.7.3
    environment:
      TZ: 'Europe/Warsaw'
      WEBPASSWORD: $PASS
      PIHOLE_DNS_: '172.70.7.2#5053'
      DNSMASQ_LISTENING: 'all'
      VIRTUAL_HOST: $LOCAL_DOMAIN_FOR_PIHOLE
    volumes:
      - '/home/kcn/docker/pihole/:/etc/pihole/'
      - '/home/kcn/docker/pihole/etc-dnsmasq.d/:/etc/dnsmasq.d/'
    restart: unless-stopped
    depends_on:
      - cloudflared

networks:
  pihole_internal:
     ipam:
       config:
         - subnet: 172.70.7.0/29
     name: pihole_internal
