#-------------------#
#    FTP server     #
#-------------------#
services:
    vsftpd:
      image: panubo/vsftpd
      ports:
      - "2121:21"
    environment:
      FTP_USER: $USER
      FTP_PASSWORD: $PASSWORD
      PASV_ADDRESS: $SERVER_IP
      PASV_PORT_RANGE: 22000-22010
    volumes:
      - "/directory:/home/vsftpd/ftpuser"

networks:
  mynetwork:
    driver: bridge