#-----------------------------------#
#    dashboard for your homelab     #
#-----------------------------------#
services:
  dash:
    image: mauricenino/dashdot:latest
    restart: unless-stopped
    privileged: true
    ports:
      - '83:3003'
    volumes:
      - /:/mnt/host:ro